
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: java src/com/keypairgenerator/Main.java
      - run: java src/com/keypairgenerator/Main.java
      - run: java src/com/keypairgenerator/Main.java
      - run: java src/com/keypairgenerator/Main.java
      - run: java src/com/keypairgenerator/Main.java
      - run: java src/com/keypairgenerator/Main.java
